function TxId = generateTxId(txOutId, txOutIndex, timestamp, address, amount)
TxId = DataHash([serializeCell(txOutId) ...
    num2str(txOutIndex) num2str(timestamp) ...
    serializeCell(address) serializeCell(amount)], 'SHA-256');
end